# Generated by Django 3.1.7 on 2021-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210314_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'создан'), ('delivered', 'доставлен'), ('processed', 'в обработке'), ('cancelled', 'отменен')], default='created', max_length=20),
        ),
    ]
