# Generated by Django 3.1.7 on 2021-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(
                    choices=[
                        ('moderation', 'на модерации'),
                        ('published', 'опубликован'),
                        ('rejected', 'отклонен')],
                    max_length=20),
                 ),
            ],
        ),
    ]
