# Generated by Django 3.1.7 on 2021-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210228_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
